message_app/message_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

message_app/polls/urls.py
from django.urls import path

from . import views



app_name = "polls"

urlpatterns = [
    path("index/",views.index, name="index"),
    
    path("<int:question_id>/",views.details, name="details"),
    
    path("<int:question_id>/results",views.results,name="results"),
    
    path("<int:question_id>/vote",views.vote,name="vote"),
    
    path("<int:question_id>/new_choice",views.new_choice,name="new_choice"),
    
    path("<int:question_id>/choice",views.choices,name="choice"),
    
    path("new_question/",views.new_question,name="new_question"),
    
]

message_app/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("Date Published")
    def __str__(self):
        return self.question_text
    def published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

message_app/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from .models import Question, Choice
from django.urls import reverse
from django.utils import timezone


# Create your views here.


from django.http import HttpResponse, HttpResponseRedirect

def results(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request,"polls/results.html", {"question":question})

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    template = loader.get_template("polls/index.html")
    context = {
        "latest_question_list" : latest_question_list
    }
    return HttpResponse(template.render(context,request))

def details(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request,"polls/detail.html",{"question":question})


def new_choice(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    new_choice_text = request.POST["new_choice"]
    if(new_choice_text):
        c = Choice.objects.create(choice_text = new_choice_text,question=question)
        c.save()
        return HttpResponseRedirect(f"../../polls/{question.id}")
    else:
        return render(
            request,
            "polls/new_choice.html",
            {
                "question":question,
                "error_message" : "You did not enter a new choice"
            }
            )


def vote(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(  
            request,
            "polls/detail.html",
            {
                "question":question,
                "error_message" : "You did not select a choice"
            }
        )
    else:
        selected_choice.votes+=1;
        selected_choice.save();
        
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    

def choices(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(
                request,
                "polls/new_choice.html",
                {
                    "question":question
                })


def new_question(request):
    try:
        question = Question.objects.create(question_text = request.POST["new_question"],pub_date=timezone.now())
        question.save()
        return HttpResponseRedirect(reverse("polls:",args=(question.id,)))
    except:
        latest_question_list = Question.objects.order_by("-pub_date")[:5]
        return render(request,
                      "polls/index.html",
                      {
                          "latest_question_list":latest_question_list
                      })

message_app/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

message_app/polls/templates/polls/index.html
<form action="{%url 'polls/new_question'%}" method ="post">
{%csrf_token%}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{%url 'polls:details' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<fieldset>
    <input type="text" name="new_question" id="new_question" placeholder="Enter your new question" value="">
</fieldset>

<input type ="submit" value="Submit new question">
</form>

message_app/polls/templates/polls/new_choice.html
<form action="{%url 'polls:new_choice' question.id%}" method = "post">

    {% csrf_token %}
    <fieldset>
        <legend><h1>{{question.question_text}}</h1></legend>
        {%if error_message%}<p><strong>{{error_message}}</strong></p>{%endif%}
        {%for choice in question.choice_set.all%}
            <ul>
                <li>{{choice.choice_text}}</li>
            </ul>
        {%endfor%}
        <input type="text" name = "new_choice" id = "new_choice" value="" placeholder="Your new choice for this question">
        </fieldset>
        <input type="submit" value="Submit new choice">
</form>

<head>

message_app/polls/templates/polls/results.html
<h1>{{question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
    
    <a href="{% url 'polls:details' question.id %}">Vote again?</a>